### ISSUE TITLE
Error during seed of Refinery Blog

### ISSUE THREAD

**Issue by abratashov** [refinery/refinerycms-blog#396] opened 2014-11-27 11:18 UTC
I bumped with problem during installation Blog extension for Refinery CMS. When I run seed for Refinery Blog it show me error:

    ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved

After debugging I found another FriendlyId error:

    ActiveRecord::RecordInvalid: Validation failed: Friendly is reserved

I solved it by moving seed.rb from blog extension to my app and little fixed it: renamed "Blog" title to "Blogs"

    # Refinery::Blog::Engine.load_seed
    ## fixed title from "Blog" to "Blogs"
    Refinery::User.all.each do |user|
      if user.plugins.where(:name => 'refinerycms_blog').blank?
        user.plugins.create(:name => "refinerycms_blog",
                            :position => (user.plugins.maximum(:position) || -1) +1)
      end
    end if defined?(Refinery::User)
    
    if defined?(Refinery::Page) and !Refinery::Page.exists?(:link_url => '/blog')
      page = Refinery::Page.create(
        :title => "Blogs",
        :link_url => "/blog",
        :deletable => false,
        :menu_match => "^/blogs?(\/|\/.+?|)$"
      )
      Refinery::Pages.default_parts.each_with_index do |default_page_part, index|
        page.parts.create(:title => default_page_part, :body => nil, :position => index)
      end
    end
 
http://stackoverflow.com/questions/27169320/error-during-seed-of-refinery-blog-activerecordrecordnotsaved-validation-fai

**Comment by bricesanchez** [comment] 2015-11-18 03:30
I'm not able to reproduce your error. I close this issue. Thanks for reporting.

**Closed by bricesanchez** 2015-11-18 03:30 UTC
Labels: Bug, Needs verification
