### ISSUE TITLE
Factory Tag Spec failed to run.

### ISSUE THREAD

**Issue by awongCM** [refinery/refinerycms-blog#422] opened 2015-03-04 11:44 UTC
Hi @parndt ,

From our previous thread, you advised me to create FactoryGirl class for my tag classes.

Which I did.

I wrote the following under `spec/factories/blog_tags.rb`

    FactoryGirl.define do
        factory :blog_tag, :class => Refinery::Blog::Tag do
            sequence(:name) { |n| "#{n}" }
        end
    end

Then I ran `rspec spec/factories/blog_tags.rb`, I got the following error

    /home/andy/Projects/Ruby/refinerycms-blog/spec/factories/blog_posts.rb:1:in `<top (required)>': uninitialized constant FactoryGirl (NameError)
      from /home/andy/.rvm/gems/ruby-2.1.2/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load'
      from /home/andy/.rvm/gems/ruby-2.1.2/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `block in load_spec_files'
      from /home/andy/.rvm/gems/ruby-2.1.2/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `each'
      from /home/andy/.rvm/gems/ruby-2.1.2/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load_spec_files'
      from /home/andy/.rvm/gems/ruby-2.1.2/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:18:in `run'
      from /home/andy/.rvm/gems/ruby-2.1.2/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
      from /home/andy/.rvm/gems/ruby-2.1.2/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `block in autorun'

I found it mind-boggling on how could this fail since refinerycmsblog already has factory-girls-rails gem inside the gemfile lock and its require statement for it is definitely in the `spec_helper.rb` file. 

I even followed this guide  https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md

to do this.

    RSpec.configure do |config|
      config.include FactoryGirl::Syntax::Methods
    end
 
So why does it happen all of a sudden?

**Comment by parndt** [comment] 2015-03-04 23:25
Did you try putting, at the top of your factory file,

```ruby
require "factory_girl"

FactoryGirl.define do
  factory :blog_tag, :class => Refinery::Blog::Tag do
    sequence(:name) { |n| "#{n}" }
  end
end
```

**Comment by awongCM** [comment] 2015-03-07 08:19
Tried that.

I got the following.

      andy@LINUXAWCM:~/Projects/Ruby/refinerycms-blog$ rspec spec/factories/blog_tags.rb
      /home/andy/Projects/Ruby/refinerycms-blog/spec/factories/blog_tags.rb:4:in `block in <top (required)>': uninitialized constant Refinery (NameError)
        from /home/andy/.rvm/gems/ruby-2.1.2/gems/factory_girl-4.2.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
        from /home/andy/.rvm/gems/ruby-2.1.2/gems/factory_girl-4.2.0/lib/factory_girl/syntax/default.rb:49:in `run'
        from /home/andy/.rvm/gems/ruby-2.1.2/gems/factory_girl-4.2.0/lib/factory_girl/syntax/default.rb:7:in `define'
        from /home/andy/Projects/Ruby/refinerycms-blog/spec/factories/blog_tags.rb:3:in `<top (required)>'
        from /home/andy/.rvm/gems/ruby-2.1.2/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load'
        from /home/andy/.rvm/gems/ruby-2.1.2/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `block in load_spec_files'

**Comment by parndt** [comment] 2015-03-08 20:59
Is your version on GitHub?

**Comment by awongCM** [comment] 2015-03-09 09:44
Nope.  Not yet.

Would you like to push my commits to my own forked branch so you can take a look at it?

**Comment by parndt** [comment] 2015-03-10 01:03
Yes, please :)

**Comment by awongCM** [comment] 2015-03-12 11:15
Sure.  It's up now. :)

**Comment by parndt** [comment] 2015-03-12 20:06
Oh wait, I just noticed that you're trying to run your factories files directly with rspec?

You should run rspec like this:

```
bundle exec rspec spec
```

If you try to run a factory file then it won't understand.

**Comment by awongCM** [comment] 2015-03-15 04:49
I ran `bundle exec rspec spec`

I got the following.

All examples were filtered out; ignoring {:focus=>true}
    .......................................FFFFFF.....F...............FF.............................................................FF

    Failures:

      1) Refinery::Blog::Post when no blog posts new blog post form create blog post should be the only blog post
         Failure/Error: page.evaluate_script("WYMeditor.INSTANCES[0].html('<p>And I love it</p>')")
         Capybara::Poltergeist::JavascriptError:
           One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
           
           ReferenceError: Can't find variable: WYMeditor
           ReferenceError: Can't find variable: WYMeditor
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
         # ./spec/features/refinery/blog/admin/posts_spec.rb:47:in `block (5 levels) in <module:Admin>'

      2) Refinery::Blog::Post when no blog posts new blog post form create blog post should belong to me
         Failure/Error: page.evaluate_script("WYMeditor.INSTANCES[0].html('<p>And I love it</p>')")
         Capybara::Poltergeist::JavascriptError:
           One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
           
           ReferenceError: Can't find variable: WYMeditor
           ReferenceError: Can't find variable: WYMeditor
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
         # ./spec/features/refinery/blog/admin/posts_spec.rb:47:in `block (5 levels) in <module:Admin>'

      3) Refinery::Blog::Post when no blog posts new blog post form create blog post should save categories
         Failure/Error: page.evaluate_script("WYMeditor.INSTANCES[0].html('<p>And I love it</p>')")
         Capybara::Poltergeist::JavascriptError:
           One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
           
           ReferenceError: Can't find variable: WYMeditor
           ReferenceError: Can't find variable: WYMeditor
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
         # ./spec/features/refinery/blog/admin/posts_spec.rb:47:in `block (5 levels) in <module:Admin>'

      4) Refinery::Blog::Post when no blog posts new blog post form create blog post with tags should succeed
         Failure/Error: page.evaluate_script("WYMeditor.INSTANCES[0].html('<p>And I also love it</p>')")
         Capybara::Poltergeist::JavascriptError:
           One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
           
           ReferenceError: Can't find variable: WYMeditor
           ReferenceError: Can't find variable: WYMeditor
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
         # ./spec/features/refinery/blog/admin/posts_spec.rb:77:in `block (5 levels) in <module:Admin>'

      5) Refinery::Blog::Post when no blog posts new blog post form create blog post with tags should be the only blog post
         Failure/Error: page.evaluate_script("WYMeditor.INSTANCES[0].html('<p>And I also love it</p>')")
         Capybara::Poltergeist::JavascriptError:
           One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
           
           ReferenceError: Can't find variable: WYMeditor
           ReferenceError: Can't find variable: WYMeditor
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
         # ./spec/features/refinery/blog/admin/posts_spec.rb:77:in `block (5 levels) in <module:Admin>'

      6) Refinery::Blog::Post when no blog posts new blog post form create blog post with tags should have the specified tags
         Failure/Error: page.evaluate_script("WYMeditor.INSTANCES[0].html('<p>And I also love it</p>')")
         Capybara::Poltergeist::JavascriptError:
           One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
           
           ReferenceError: Can't find variable: WYMeditor
           ReferenceError: Can't find variable: WYMeditor
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
         # ./spec/features/refinery/blog/admin/posts_spec.rb:77:in `block (5 levels) in <module:Admin>'

      7) Refinery::Blog::Post with multiple users create blog post with alternate author belongs to another user
         Failure/Error: page.evaluate_script("WYMeditor.INSTANCES[0].html('<p>I totally did not write it.</p>')")
         Capybara::Poltergeist::JavascriptError:
           One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
           
           ReferenceError: Can't find variable: WYMeditor
           ReferenceError: Can't find variable: WYMeditor
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
               at phantomjs://webpage.evaluate():1
         # ./spec/features/refinery/blog/admin/posts_spec.rb:169:in `block (4 levels) in <module:Admin>'

      8) Tags admin when there are some tags should say there's at least one tag on the page
         Failure/Error: tags.size.should be >= 1
           expected: >= 1
                got:    0
         # ./spec/features/refinery/blog/admin/tags_spec.rb:42:in `block (3 levels) in <top (required)>'

      9) Tags admin when there are no tags should say there are not tags on the page
         Failure/Error: subject.class.delete_all
         NoMethodError:
           undefined method `delete_all' for String:Class
         # ./spec/features/refinery/blog/admin/tags_spec.rb:49:in `block (3 levels) in <top (required)>'

      10) Refinery::Blog::Tag validations does not have an empty value
         Failure/Error: FactoryGirl.build(:blog_tag).should_not_be_valid
         ArgumentError:
           wrong number of arguments (0 for 1)
         # ./app/models/refinery/blog/tag.rb:9:in `initialize'
         # ./spec/models/refinery/blog/tag_spec.rb:10:in `block (3 levels) in <module:Blog>'

      11) Refinery::Blog::Tag validations does not have a nil value
         Failure/Error: FactoryGirl.build(:blog_tag).should_not_be_valid
         ArgumentError:
           wrong number of arguments (0 for 1)
         # ./app/models/refinery/blog/tag.rb:9:in `initialize'
         # ./spec/models/refinery/blog/tag_spec.rb:14:in `block (3 levels) in <module:Blog>'


The firs two alerted errors are pertaining to the issue #409 which I last reported a month ago....

**Comment by awongCM** [comment] 2015-03-15 08:31
Now that #409 is resolved, I got the correct output of errors we're more interested in seeing.

In that last comment, rspec complains the following line

    5) Refinery::Blog::Tag validations does not have an empty value
         Failure/Error: FactoryGirl.build(:blog_tag).should_not_be_valid
         ArgumentError:
           wrong number of arguments (0 for 1)
         # ./app/models/refinery/blog/tag.rb:9:in `initialize'

In my `/app/models/refinery/blog/tag.rb`, I have the following

    module Refinery
        module Blog
            class Tag < ActsAsTaggableOn::Tag

              def initialize(object)
                    super name: object.name
                    @object = object
              end

             ..................................................
             ..................................................

            end
        end
    end

Why would it complain on the initialize line?  Did I not provide a parameter in my FactoryGirl class for Tag spec object? like so

    module Refinery
      module Blog
        describe Tag do
            let(:tag) { FactoryGirl.create(:blog_tag) }

            describe "validations" do
                it "does not have an empty value" do
                    FactoryGirl.build(:blog_tag).should_not_be_valid
                end

                it "does not have a nil value" do
                    FactoryGirl.build(:blog_tag).should_not_be_valid
                end
            end
        end
      end
    end

**Comment by awongCM** [comment] 2015-03-22 21:51
Any thoughts on this one @parndt?

**Comment by parndt** [comment] 2015-03-22 22:11
The problem is this line:

```ruby
def initialize(object)
```

You can't accept an argument into the `initialize` method

**Comment by awongCM** [comment] 2015-03-23 07:02
Okay. So how can I make it accept an argument in the `initialise` method for my rspec to pass? Or I just couldn't do so?

**Comment by bricesanchez** [comment] 2015-11-18 03:25
Is it fixed for you @awongCM ?

**Comment by awongCM** [comment] 2015-11-19 07:34
Nope.

But looks like I don't have time to look into it.

Perhaps will check it next year when I look into Ruby again at some point.

**Comment by bricesanchez** [comment] 2015-11-19 13:43
Ok, i close this issue.

**Closed by bricesanchez** 2015-11-19 13:43 UTC
Labels: Bug, Won't fix
